import shm_variables as shm
# target columns with the prefix "shm." are columns related to the Stroke healhcare model
column_mapping = {
    "ICO": shm.id,
    "provider": shm.provider,
    "SIDZAR_POPIS_KRAJ": "group",
    "NÁZOV NEMOCNICE SKRÁTENÝ": shm.hospital_name,
    "PACVEK": shm.age,
    "PACPOHLAVIE": shm.sex,
    "PACDATVYK": shm.onset_date,
    "PACCASVYK": shm.onset_time,
    "WAKE_UP_STROKE_1": shm.wakeup_stroke,
    "TRANSPORT_TYP": shm.inhospital_stroke,
    "TRANSPORT_SPE": shm.arrival_mode,
    "DATUM_LEKAR": shm.hospital_timestamp,
    "JIS_ARO": shm.hospitalized_in,
    "STAV_NHISS_2": shm.nihss_score,
    "STAV_M_RANKIN_2": shm.prestroke_mrs,
    "STAV_TK_SYSTOLICKY": shm.systolic_pressure,
    "STAV_TK_DIASTOLICKY": shm.diastolic_pressure,
    "OA_TIA": "risk_tia",
    "OA_ISCHEMICKA_CMP": shm.risk_previous_ischemic_stroke,
    "OA_HEMORAGICKA_CMP": shm.risk_previous_hemorrhagic_stroke,
    "OA_HYPERTENZIA": shm.risk_hypertension,
    "OA_HYPERLIPIDEMIA": shm.risk_hyperlipidemia,
    "OA_D_PAD": shm.risk_diabetes,
    "OA_D_INZULIN": shm.before_onset_antidiabetics,
    "OA_FAJCENIE": shm.risk_smoker_last_10_years,
    "OA_FIBRILACIA_PRED": shm.risk_atrial_fibrillation,
    "OA_IM": shm.risk_coronary_artery_disease_or_myocardial_infarction,
    "RA_CMP": shm.risk_previous_stroke,
    "OA_HYPERTENZIA_LIEC": shm.before_onset_antihypertensives,
    "OA_ANTIKOAGULANCIA": "before_onset_anticoagulants",
    "OA_ASPIRIN": shm.before_onset_asa,
    "OA_CLOPIDOGREL": shm.before_onset_clopidogrel,
    "OA_KONTRACEPTIVA": shm.before_onset_contraception,
    "OA_STATINY": shm.before_onset_statin,
    "CT_MR_VYSETRENIE": shm.imaging_type,
    "CT_ANGIO": "ct_angio",
    "CT_PERFUZNE": "ct_perfusion",
    "DATUM_CT": shm.imaging_timestamp,
    "KKD_TYP_SPEC": shm.stroke_type,
    "NL_TROMBOLYZA": shm.thrombolysis,
    "NL_DATUM_TROMBOLYZA": shm.bolus_timestamp,
    "DNTL_MIMO_CAS": "no_ivt_reason_time_window",
    "DNTL_DEFICIT": "no_ivt_reason_mild_deficit",
    "ENDO_VYKON": shm.thrombectomy,
    "DATUM_ENDO_V": shm.puncture_timestamp,
    "DATUM_REKANALIZACIE": shm.reperfusion_timestamp,
    "TICI": shm.mtici_score,
    "NMT_MIMO_CAS": "no_mt_reason_time_window",
    "DMT_DEFICIT": "no_mt_reason_mild_deficit",
    "DMT_PREMORBIDITA": "no_mt_reason_premorbidity",
    "REKANAL_KRVACANIE": shm.mt_complications_perforation,
    "ETIO_HEM_CMP": "bleeding_reasons",
    "UKON_FIB_PREDSIEN": shm.atrial_fibrillation_or_flutter,
    "KAROTIDA": shm.carotid_arteries_imaging,
    "ETIO_ISCH_CMP": "etiology",
    "DYSFAGIA_VYS": shm.swallowing_screening_done,
    "DYSFAGIA": shm.swallowing_screening_timing,
    "DYSFAGIA_SPEC": shm.swallowing_screening_type,
    "UKON_SPOSOB": shm.discharge_destination,
    "UKON_PREKLAD_VYBER": shm.discharge_facility_department,
    "UKON_DATUM": shm.discharge_date,
    "UKON_MRANKIN_2": shm.discharge_mrs,
    "UKON_MRANKIN_po 3 mesiacoch": shm.three_m_mrs,
    "UKON_NIHSS_2": shm.discharge_nihss_score,
    "UKON_ASA": shm.discharge_asa,
    "UKON_CLOPIDOGREL": shm.discharge_clopidogrel,
    "UKON_WARFARIN": shm.discharge_warfarin,
    "UKON_HEPARIN": shm.discharge_heparin,
    "UKON_STATIN": shm.discharge_statin,
    "UKON_DOAK":"discharge_doak",
    "UKON_ANTIDEPRESIVA": "discharge_other2",
    "UKON_NOOTROPIKA": shm.discharge_other,
}
